services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: CompileDaemon --command="./election"
    environment:
      - GO111MODULE=on
    networks:
      - election
  pgsql:
      image: 'postgres:16.0-bookworm'
      ports:
          - '5432:5432'
      environment:
          PGPASSWORD: 'password'
          POSTGRES_DB: 'password'
          POSTGRES_USER: 'sail'
          POSTGRES_PASSWORD: 'password'
      volumes:
          - 'election-pgsql:/var/lib/postgresql/data'
      networks:
          - election
  adminer:
      image: adminer:4.8.1
      restart: always
      ports:
        - 6969:8080
      environment:
        ADMINER_DESIGN: dracula
      networks:
          - election
  frontend_app:
      build: ./frontend
      container_name: election-frontend
      restart: always
      ports:
        - '3000:3000'
        - '24678:24678'
      environment:
        - NUXT_PORT=3000
        - CHOKIDAR_USEPOLLING=true
      command: 'bun run dev'
      volumes:
        - ./frontend:/app
        - /app/node_modules
      networks:
        - election

networks:
    election:
        driver: bridge
volumes:
    election-pgsql:
        driver: local
